version: '3.9'

services:
  web:
    build: ./client
    ports:
      - "5000"
    depends_on:
      - server
    networks:
      - mynetwork

  server:
    build: ./app
    ports:
      - "5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
